apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw
  labels:
    app: hw

spec:
  replicas: 2
  selector:
    matchLabels:
      app: hw
  template:
    metadata:
      labels:
        app: hw
    spec:      
      containers:
      - image: nginx:latest
        name: app
        ports:
          - containerPort: 80
    