apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hw-app
  name: hw-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw-app
  template:
    metadata:
      labels:
        app: hw-app
    spec:
      containers:
      - image: localhost:5000/local-nginx
        name: local-nginx
        # imagePullPolicy: Never
        ports:
        - containerPort: 80
        