apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  labels:
    app: hw-app
  name: hw-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw-app
  template:
    metadata:
      labels:
        app: hw-app
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
